# Generated by Django 5.1.15 on 2026-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="business_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="country",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
