# Generated by Django 5.1.15 on 2026-02-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_accountprofile_email_verified_at_accountemailotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountemailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("email_verify", "Email Verify"),
                    ("password_reset", "Password Reset"),
                    ("login", "Login"),
                ],
                max_length=32,
            ),
        ),
    ]
