"""
Django settings for wasla_sore project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure--cop!lr6o*&sny4$%3&-=)l18w7-lf+7$a8itl+q%qz!4p1yll",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1").strip().lower() in ("1", "true", "yes")
ENVIRONMENT = os.getenv("ENVIRONMENT", "development").strip().lower() or "development"
TEST_OTP_CODE = os.getenv("TEST_OTP_CODE", "12345").strip() or "12345"

ALLOWED_HOSTS = [
        "w-sala.com",
        "www.w-sala.com",
        
        "76.13.143.149",
        "localhost",
        "127.0.0.1"
        
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt.token_blacklist",
    "apps.accounts.apps.AccountsConfig",
    "apps.sms.apps.SmsConfig",
    "apps.notifications.apps.NotificationsConfig",
    "apps.tenants.apps.TenantsConfig",
    "apps.catalog.apps.CatalogConfig",
    "apps.customers.apps.CustomerConfig",
    "apps.orders.apps.OrderConfig",
    "apps.payments.apps.PaymentConfig",
    "apps.plugins.apps.PluginsConfig",
    "apps.reviews.apps.ReviewsConfig",
    "apps.shipping.apps.ShippingConfig",
    "apps.subscriptions.apps.SubscriptionConfig",
    "apps.wallet.apps.WalletConfig",
    "apps.emails.apps.EmailsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "apps.tenants.middleware.TenantMiddleware",
    "apps.tenants.middleware.TenantLocaleMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "apps.accounts.middleware.OnboardingRedirectMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "wasla_sore.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.template.context_processors.i18n",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wasla_sore.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = os.getenv("DJANGO_LANGUAGE_CODE", "ar").strip() or "ar"

LANGUAGES = [
    ("ar", "Arabic"),
    ("en", "English"),
]

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
#STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = Path(os.getenv("DJANGO_STATIC_ROOT", str(BASE_DIR / "staticfiles")))

MEDIA_URL = "/media/"
MEDIA_ROOT = Path(os.getenv("DJANGO_MEDIA_ROOT", str(BASE_DIR / "media")))

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"

AUTHENTICATION_BACKENDS = [
    "apps.accounts.infrastructure.auth_backends.PhoneOrEmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        "apps.tenants.interfaces.api.permissions.HasTenantAccess",
    ),
    "DEFAULT_THROTTLE_RATES": {
        "auth": "10/min",
        "onboarding": "30/min",
    },
}

OTP_PROVIDER_REGISTRY = {
    "email": "apps.accounts.infrastructure.otp_providers.email.EmailOtpProvider",
    "sms": "apps.accounts.infrastructure.otp_providers.sms.SmsOtpProvider",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

# Reverse-proxy security (optional; controlled via env vars)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "0").strip().lower() in ("1", "true", "yes")
SESSION_COOKIE_SECURE = os.getenv("DJANGO_SESSION_COOKIE_SECURE", "0").strip().lower() in ("1", "true", "yes")
CSRF_COOKIE_SECURE = os.getenv("DJANGO_CSRF_COOKIE_SECURE", "0").strip().lower() in ("1", "true", "yes")

# SMS (multi-gateway)
SMS_DEFAULT_PROVIDER = os.getenv("SMS_DEFAULT_PROVIDER", "console").strip() or "console"
SMS_DEFAULT_SENDER_NAME = os.getenv("SMS_DEFAULT_SENDER_NAME", "Wasla").strip() or "Wasla"
SMS_DEFAULT_COUNTRY_CODE = os.getenv("SMS_DEFAULT_COUNTRY_CODE", "").strip()

SMS_PROVIDERS = {
    "console": {
        "sender_name": SMS_DEFAULT_SENDER_NAME,
    },
    "taqnyat": {
        "base_url": os.getenv("SMS_TAQNYAT_BASE_URL", "https://api.taqnyat.sa").strip() or "https://api.taqnyat.sa",
        "bearer_token": os.getenv("SMS_TAQNYAT_BEARER_TOKEN", "").strip(),
        "sender_name": os.getenv("SMS_TAQNYAT_SENDER_NAME", SMS_DEFAULT_SENDER_NAME).strip() or SMS_DEFAULT_SENDER_NAME,
        "timeout_seconds": int(os.getenv("SMS_TAQNYAT_TIMEOUT_SECONDS", "10") or "10"),
        "include_bearer_as_query_param": (os.getenv("SMS_TAQNYAT_INCLUDE_QUERY_TOKEN", "0").strip().lower() in ("1", "true", "yes")),
    },
}

OTP_PROVIDER_REGISTRY = {
    "email": "apps.accounts.infrastructure.otp_providers.email.EmailOtpProvider",
    "sms": "apps.accounts.infrastructure.otp_providers.sms.SmsOtpProvider",
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
